package com.spark.bitrade.messager;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member_mail
 */
public class MemberMail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 站内信  用户ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.from_member_id
     *
     * @mbg.generated
     */
    private Long fromMemberId;

    /**
     * Database Column Remarks:
     * 用户ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.to_member_id
     *
     * @mbg.generated
     */
    private Long toMemberId;

    /**
     * Database Column Remarks:
     * 站内信 主题
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.subject
     *
     * @mbg.generated
     */
    private String subject;

    /**
     * Database Column Remarks:
     * 站内信 内容表ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.content_id
     *
     * @mbg.generated
     */
    private Long contentId;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     * 站内信 状态 0未读 1 已读
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_mail.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.id
     *
     * @return the value of member_mail.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.id
     *
     * @param id the value for member_mail.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.from_member_id
     *
     * @return the value of member_mail.from_member_id
     * @mbg.generated
     */
    public Long getFromMemberId() {
        return fromMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.from_member_id
     *
     * @param fromMemberId the value for member_mail.from_member_id
     * @mbg.generated
     */
    public void setFromMemberId(Long fromMemberId) {
        this.fromMemberId = fromMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.to_member_id
     *
     * @return the value of member_mail.to_member_id
     * @mbg.generated
     */
    public Long getToMemberId() {
        return toMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.to_member_id
     *
     * @param toMemberId the value for member_mail.to_member_id
     * @mbg.generated
     */
    public void setToMemberId(Long toMemberId) {
        this.toMemberId = toMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.subject
     *
     * @return the value of member_mail.subject
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.subject
     *
     * @param subject the value for member_mail.subject
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.content_id
     *
     * @return the value of member_mail.content_id
     * @mbg.generated
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.content_id
     *
     * @param contentId the value for member_mail.content_id
     * @mbg.generated
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.create_time
     *
     * @return the value of member_mail.create_time
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.create_time
     *
     * @param createTime the value for member_mail.create_time
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_mail.status
     *
     * @return the value of member_mail.status
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_mail.status
     *
     * @param status the value for member_mail.status
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}