# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


#单个账户交易测试(tcc try测试)
GET http://localhost:6028/acct/api/v2/tas01/tcc01
###

#单个账户交易测试(tcc try测试)
GET http://localhost:6028/acct/api/v2/tas01/tcc02
###



#单个账户交易测试(tcc confirm 测试)
GET http://localhost:6028/acct/api/v2/tas01/tcc2?id=1149261887467225090
###

#单个账户交易测试(tcc cancel 测试)
GET http://localhost:6028/acct/api/v2/tas01/tcc3?id=1149261563356577794
###
